server:
  port: 9091
#  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver      
#    url: jdbc:mysql://104.168.141.141:3306/at_once?characterEncoding=utf-8&serverTimezone=GMT%2B8   # 设置时区为东八区北京时间
    url: jdbc:mysql://localhost:3306/at_once?characterEncoding=utf-8&serverTimezone=GMT%2B8   # 设置时区为东八区北京时间
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  application:
    name: photos-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # spring默认使用jackson解析包返回json，配置日期的返回方式，
  jackson:
    time-zone: GMT+8    # 配置时区，东八区
    date-format: yyyy-MM-dd HH:mm:ss  # 默认返回时间格式

# 向spring容器保存图片的保存地址
picPath: G:/test/
#picPath: C:/resource/img/
#picPath: /tmp